# conda env create -f environment.yml
name: genesis-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - lume-base
#  - genesis2=*=mpi_mpich*
# Developer
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - matplotlib
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python
  - pre-commit
  - flake8
  - pip
  - pip:
    - ufmt
#  - pip:
#    - git+git://github.com/some/repo

